spring:
  resources:
    static-locations: [classpath:/static/]
  datasource:
    url: jdbc:mysql://localhost:3306/ssmbuild?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.param.bootbooks.*
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false;
        allow: 61.144.96.126,127.0.0.1
      web-stat-filter:
        enabled: true
        url-pattern: /*

      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  jdbc:
    template:
      query-timeout: 3
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 9090

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
